<?php

namespace OC\BlogBundle\Repository;

use OC\BlogBundle\Entity\Commentaire;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentsForBlog($episodeId)
    {
        $qb = $this->createQueryBuilder('c')
                   ->where('c.episode = :episode_id')->setParameter('episode_id', $episodeId)                   
                   ->andWhere('c.modere = false')
                   ->addOrderBy('c.creation');           
        
        return $qb->getQuery()->getResult();
    }
    
    public function getCommentByStatut($statut){
        $qb = $this->createQueryBuilder('c')
                   ->addOrderBy('c.creation','DESC'); 
        
        switch ($statut){
            case Commentaire::LICITE:
                $qb->where('c.signalement=false AND c.modere=false');
                break;
            case Commentaire::SIGNALE:
                $qb->where('c.signalement=true AND c.modere=false');
                break;
            case Commentaire::MODERE:
                $qb->where('c.signalement=false AND c.modere=true');
                break;
        }
        
        return $qb->getQuery()->getResult();
    }
}
