<?php

namespace OC\BlogBundle\Repository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends \Doctrine\ORM\EntityRepository {

    public function findByNumeroWithCommentaires($numero) {
        $q = $this->createQueryBuilder('e')
                ->leftJoin('e.commentaires', 'c')->addSelect('c')
                ->where('e.numeroEpisode = :numeroEpisode')
                ->setParameter('numeroEpisode', $numero);
        
        return $q->getQuery()->getOneOrNullResult();
    }

    public function getNbEpisodes(){
        $q=$this->createQueryBuilder('e')
                ->select('MAX(e.numeroEpisode)');
        
        return $q->getQuery()->getSingleScalarResult();          
    }
    
}
