oc_blog_admin_episode:
    resource: "@OCBlogBundle/Resources/config/routing/episode.yml"
    prefix:   /admin/episode

oc_blog_homepage:
    path:     /{numeroEpisode}
    defaults: { _controller: OCBlogBundle:Default:index, numeroEpisode: 1 }
    requirements: 
        numeroEpisode: \d+

oc_blog_admin_commentaire:
        resource: "@OCBlogBundle/Resources/config/routing/commentaire.yml"
        prefix:   /admin/commentaire
        
oc_blog_signalement:
    path: /signalement/{commentaire}
    defaults:  { _controller: OCBlogBundle:Default:signalementCommentaire}

